import Script from 'next/script'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Sidebar from '../components/Sidebar'
import VideoState from '../context/videos/VideoState'
import '../styles/globals.css'
import '../styles/nProgress.css'
import Head from 'next/head'
import Router from 'next/router'
import NProgress from 'nprogress'

function MyApp({ Component, pageProps }) {

  Router.events.on("routeChangeStart", (ur=-0) => {
    console.log('routeChangeStart');
    NProgress.start();

  })
  Router.events.on("routeChangeComplete", (url) => {
    console.log('routeChangeComplete');
    NProgress.done();
  })


  return (
    <>

      <Head>
        <title>Free HD Porn Videos &amp; Sex Movies - Porno, XXX, Porn Tube | Chutlunds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='asg_verification' content='vVcWCcbbgmnqv221hpAjPojb' />
        <meta name="exoclick-site-verification" content="6b1112fe173bdf782d96975e70bd4b95"></meta>
        <meta name="description" content="Watch more than 5 million Porn Videos on xHamster for free. Stream new XXX tube movies online, browse sex photos, date girls to fuck at !" />
        <meta name="description" content="Chutlunds is the world’s leading free porn site. Choose from millions of hardcore videos that stream quickly and in high quality, including amazing VR Porn. The largest adult site on the Internet just keeps getting better. We have more pornstars and real amateurs than anyone else. It’s fast, it’s free, it’s Chutlunds!" />

        <meta name="hilltopads-site-verification" content="28c33bbf5c61164c74b2bdfcc2ff1d44bc9c45b5" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VideoState>

        <Navbar />
        <div className=''>
          <Component {...pageProps} />
        </div>
        <hr />
        <Footer />
      </VideoState>
    </>
  )
}

export default MyApp
